In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [2]:
dataframe=pd.read_csv("C:\\Users\\DIVYA\\Documents\\MACHINELEARNINGWORKSHOPFILES\\RAVDESS,TESS---new.csv")

## SPLITTING THE DATA

In [3]:
from sklearn.preprocessing import LabelEncoder
dataframe['Emotion']=LabelEncoder().fit_transform(dataframe['Emotion'])
y=dataframe.iloc[:,-1]
x=dataframe.drop("Emotion",axis=1)
x=x.iloc[:,1:]

xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.3,random_state=4)

In [4]:
print(xtrain.shape,xtest.shape)

(2968, 180) (1272, 180)


In [5]:
print(ytrain.shape,ytest.shape)

(2968,) (1272,)


## MLP CLASSIFIER

In [6]:
model=MLPClassifier(alpha=0.01, batch_size=32, epsilon=1e-08, hidden_layer_sizes=(300,), learning_rate='adaptive', max_iter=500)

In [7]:
model.fit(xtrain,ytrain)

MLPClassifier(alpha=0.01, batch_size=32, hidden_layer_sizes=(300,),
              learning_rate='adaptive', max_iter=500)

In [45]:
#change shape of ytrain

In [8]:
ypred=model.predict(xtest)

## ACCUARACY

In [9]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_true=ytest, y_pred=ypred)*100

85.53459119496856

## CLASSIFICATION REPORT

In [48]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       174
           1       0.75      0.28      0.41        53
           2       0.81      0.87      0.84       196
           3       0.89      0.85      0.87       187
           4       0.84      0.84      0.84       170
           5       0.79      0.87      0.83       142
           6       0.78      0.88      0.83       179
           7       0.88      0.87      0.87       171

    accuracy                           0.84      1272
   macro avg       0.83      0.79      0.80      1272
weighted avg       0.84      0.84      0.84      1272



## CONFUSION MATRIX

In [49]:
print(confusion_matrix(ytest,ypred))

[[156   0   7   0   6   2   0   3]
 [  0  15   4   3   1  16  14   0]
 [  2   1 170   5   4   3   4   7]
 [  2   0   5 159   6   1  12   2]
 [  8   0   4   6 142   2   3   5]
 [  1   2   4   2   2 123   7   1]
 [  0   2   4   2   5   6 158   2]
 [  1   0  12   1   3   2   4 148]]


## Testing

In [72]:
ynow=model.predict(xtest[101])

KeyError: 101

In [54]:
xtest.shape

(1272, 180)

In [87]:
xnow=xtest.iloc[1,:].to_frame().transpose()

In [88]:
xnow.shape

(1, 180)

In [89]:
ynow=model.predict(xnow)

In [90]:
ynow

array([6], dtype=int64)

In [95]:
ytest.iloc[1]

6

## Saving the model

In [14]:
import pickle
filename = 'ann_model.sav'
pickle. dump(model, open(filename, 'wb'))
# load the model from disk.
loaded_model = pickle. load(open(filename, 'rb'))
print("model saved")

model saved
